
import { createMdxPrimitives } from "./components/docs/mdx-primitives"
import {
    Callout,
    Accordion,
    AccordionItem,
    CodeBlock,
    Tabs,
    Tab,
    Image,
    Video,
    Card,
    CardGrid,
    ImageCard,
    ImageCardGrid,
    Steps,
    Step,
    Icon,
    Mermaid,
    Math,
    Columns,
    Column,
    Badge,
    Tooltip,
    Frame,
    ApiEndpoint,
    ApiParams,
    ApiResponse,
    ApiPlayground,
    ApiReference
} from "./components/index"

// Filter out server-only components from ClientComponents if necessary,
// but relying on "use client" directives and tsup externals is better.
// In the server bundle, ClientComponents will be imported from the Client Entry,
// so they will be Client References.

export const mdxComponents = {
    ...createMdxPrimitives({ CodeBlock }),
    CodeBlock,
    Callout,
    Accordion,
    AccordionItem,
    Tabs,
    Tab,
    Image,
    Video,
    Card,
    CardGrid,
    ImageCard,
    ImageCardGrid,
    Steps,
    Step,
    Icon,
    Mermaid,
    Math,
    Columns,
    Column,
    Badge,
    Tooltip,
    Frame,
    ApiEndpoint,
    ApiParams,
    ApiResponse,
    ApiPlayground,
    ApiReference
}
